config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {}

  root to: "pages#home"
  get "about", to: "pages#about"
  get "contact", to: "contacts#new"
  get "policies", to: "pages#policies"

  resources :contacts, only: [:new, :create]
  get "blog", to: "pages#blog"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :bookings, only: [:index, :show, :destroy, :update, :new, :create] do
    member do
      get :payment
      get :show_qr
      patch :accept
      patch :decline
    end
  end

  resources :islands, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create]
  end
end

app/models/island.rb
class Island < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos
  has_one_attached :portal_photo

  has_many :reviews
  has_many :start_bookings, class_name: 'Booking', foreign_key: 'start_island_id'
  has_many :end_bookings, class_name: 'Booking', foreign_key: 'end_island_id'
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_island, only: [:show, :edit, :update, :destroy]

  def index
    @islands = Island.all
    # The `geocoded` scope filters only islands with coordinates
    @markers = @islands.geocoded.map do |island|
      {
        lat: island.latitude,
        lng: island.longitude
      }
    end
  end

  def show
    # @island = Island.find(params[:id])
    @marker =
      {
        lat: @island.latitude,
        lng: @island.longitude
      }
    @reviews = Review.where(island_id: @island.id)
    @booking = Booking.new
  end

  def create
  end

  def new
  end

  def update
  end

  def destroy
  end

  private

  def island_params
    params.require(:island).permit(:start_date, :end_date)
  end

  def set_island
    @island = Island.find(params[:id])
  end
end

app/views/islands/index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @islands.each do |island| %>
      <tr>
        <td><%= island.name %></td>
        <td><%= link_to 'Show', island_path(island) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/islands/show.html.erb
<script src='https://api.mapbox.com/mapbox-gl-js/v3.3.0/mapbox-gl.js' data-turbolinks-track></script>
<div class="island-content my-4" id="islandPictures">
  <%= link_to :back, class:"back-btn" do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  <%= image_tag @island.portal_photo, class:"d-block w-100 portal" %>


  <% @island.photos.each do |photo| %>
    <%= image_tag photo, class:"d-block w-100 other" %>

  <% end %>


</div>

<div id="island" class="island-content">


  <div class="description-island">
    <h1>
      Teleport to <%= @island.name %> island !
    </h1>
    <br>
    <br>
    <br>
    <p>
      <%= @island.description %>
    </p>
    <p>
      <b>1. Cultural Diversity:</b> <%= @island.cul_diversity %>
    </p>
    <p>
      <b>2. Geographic Features:</b> <%= @island.geo_features %>
    </p>
    <p>
      <b>3. Accessibility and Transportation:</b> <%= @island.access_transport %>
    </p>
    </p>
    <p>
      <b>BONUS | Good to know:</b> <%= @island.practical_info %>
    </p>
  </div>

  <div class="booking-container">
                <h2 class="header-gradient">Get started now</h2>
                <%= simple_form_for @booking do |f| %>
                    <div class="input-group-container">
                        <div class="input-group gap-1">
                            <%= f.input :start_date,
                                        as: :string,
                                        input_html: { data: { controller: "datepicker" },
                                        class: 'form-select'
                                        },
                                        wrapper_html: { class: 'booking-form' },
                                        label_html: { class: 'input-group-text' }
                            %>
                                        <%# island start %>
                            <%= f.input :start_island_id,
                                        collection: Island.all,
                                        label_method: :name,
                                        value_method: :id,
                                        include_blank: false,
                                        wrapper_html: { class: 'booking-form' },
                                        label_html: { class: 'input-group-text' },
                                        input_html: { class: 'form-select' }
                            %>
                                        <%# island end %>
                            <%# island end %>
                            <%= f.input :end_island_id,
                                        collection: Island.all,
                                        label_method: :name,
                                        value_method: :id,
                                        include_blank: false,
                                        wrapper_html: { class: 'booking-form' },
                                        label_html: { class: 'input-group-text' },
                                        input_html: { class: 'form-select' },
                                        selected: @island.id,
                                        readonly: true,
                                        disabled: true

                            %>
                        </div>
                        <div class="input-group second">
                            <%= f.input :adults, collection: 1..10, selected: 1, wrapper_html: { class: 'booking-form' },
                            label_html: { class: 'input-group-text' },
                            input_html: { class: 'form-select' }
                            %>
                            <%= f.input :kids, collection: 0..10, selected: 0,
                            wrapper_html: { class: 'booking-form' },
                            label_html: { class: 'input-group-text' },
                            input_html: { class: 'form-select' }
                            %>
                            <%= f.input :baggages, collection: 0..10, selected: 0,
                            wrapper_html: { class: 'booking-form' },
                            label_html: { class: 'input-group-text' },
                            input_html: { class: 'form-select' }
                            %>
                            <%= f.input :pets, collection: 0..10, selected: 0,
                            wrapper_html: { class: 'booking-form' },
                            label_html: { class: 'input-group-text' },
                            input_html: { class: 'form-select' }
                            %>
                        </div>
                </div>

              <% if user_signed_in? %>
                <%= f.button :submit, 'Teleport', class: 'btn main-cta-color-BonWup-book' %>
              <% else %>
                <button
                  type="button"
                  class="btn main-cta-color-BonWup-book"
                  data-bs-toggle="modal"
                  data-bs-target="#loginModal"
                >
                  Teleport
                </button>
              <% end %>
            <% end %>
          </div>

</div>












<div class="island-content my-4">
  <div class="map-island"
    data-controller="map-single"
    data-map-single-marker-value="<%= @marker.to_json %>"
    data-map-single-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  >
  </div>
</div>

<div class="island-content my-4">
  <div class="my-3">
    <%= pluralize(@island.reviews.count, "review") %>
  </div>
  <div class="reviews-container">
    <% @reviews.each do |review| %>
      <div class="review-card">
      <h3><%= review.booking.user.first_name%> <%= review.booking.user.last_name%></h3>
        <p>
          <%= review.comment %>
        </p>
        <% review.rating.times do %>
          <i class="fa-solid fa-star"></i>
        <% end %>
      </div>
    <% end %>
  </div>

</div>


<% unless user_signed_in? %>
  <%= render 'shared/login_modal' %>
<% end %>

app/views/islands/test.html.erb
    <%= f.input :start_island_id,
              collection: Island.all,
              label_method: :name,
              value_method: :id,
              include_blank: false,
              selected: @island.id,
              disabled: true,
              readonly: true
              %>
              <%# island end %>
    <%# island end %>
    <%= f.input :end_island_id,
              collection: Island.all,
              label_method: :name,
              value_method: :id,
              include_blank: false %>