config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {}

  root to: "pages#home"
  get "about", to: "pages#about"
  get "contact", to: "contacts#new"
  get "policies", to: "pages#policies"

  resources :contacts, only: [:new, :create]
  get "blog", to: "pages#blog"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :bookings, only: [:index, :show, :destroy, :update, :new, :create] do
    member do
      get :payment
      get :show_qr
      patch :accept
      patch :decline
    end
  end

  resources :islands, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create]
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :start_island, class_name: 'Island'
  belongs_to :end_island, class_name: 'Island'
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy, :payment, :show_qr]

  def index
    @bookings = Booking.where(user: current_user).includes(:start_island, :end_island)
  end

  def show
    # @booking = Booking.find(params[:id])
  end


  def create
    puts "create booking"

    @booking = Booking.new(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to payment_booking_path(@booking)
    else
      render :new
    end


  end

  def new
    @island = Island.find(params[:island_id]) if params[:island_id]
    @islands = Island.all
    @booking = Booking.new

  end

  def update
  end

  def destroy
  end

  # custom routes
  def payment
    # Calculate the distance between the two islands
    @distance = @booking.start_island.distance_to(@booking.end_island)
  end

  def show_qr
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :start_island_id, :end_island_id, :pets, :baggages, :kids, :adults)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/views/bookings/index.html.erb
<div class="booking-table-container">
  <table class="table table-hover" id="booking-table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Date</th>
        <th scope="col">Time</th>
        <th scope="col">Start Island <i class="fa-solid fa-arrow-right"></i> End Island</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% counter = 1 %>
      <% @bookings.each do |booking| %>
        <tr>
          <th scope="row"><%= counter %></th>
          <td><%= booking.start_date.strftime("%B %d, %Y") unless booking.start_date.nil? %></td>
          <td><%= booking.start_date.strftime("%H:%M") unless booking.start_date.nil? %></td>
          <td>
            <%= "#{booking.start_island.name} " %>
            <i class="fa-solid fa-arrow-right">
            </i><%= " #{booking.end_island.name}" %>
          </td>
          <td>
            <%= link_to show_qr_booking_path(booking) do %>
              <i class="fa-solid fa-eye"></i>
            <% end %>
          </td>
        </tr>
        <% counter += 1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for @booking do |f| %>
  <%= f.input :start_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
            <%# island start %>
  <%= f.input :start_island_id,
            collection: Island.all,
            label_method: :name,
            value_method: :id,
            include_blank: false %>
            <%# island end %>
  <%# island end %>
  <%= f.input :end_island_id,
            collection: Island.all,
            label_method: :name,
            value_method: :id,
            include_blank: false %>
  <%= f.input :adults, collection: 1..10, selected: 1 %>
  <%= f.input :kids, collection: 0..10, selected: 0 %>
  <%= f.input :pets, collection: 0..10, selected: 0 %>
  <%= f.input :baggages, collection: 0..10, selected: 0 %>
  <div class="d-grid gap-2 d-flex">
    <div class="form-actions">
      <% if @show_checkbox_recaptcha %>
        <%= recaptcha_tags %>
      <% else %>
        <%= recaptcha_v3(action: 'login', class: 'btn main-cta-color', site_key: ENV['RECAPTCHA_SITE_KEY_V3']) %>
      <% end %>
        <%= f.button :submit, "Send", class: 'main-cta-color-BonWup' %>
    </div>
  </div>
<% end %>

app/views/bookings/payment.html.erb
<div class="d-flex justify-content-center mt-5 mb-5" id="payment">
  <div class="row g-3 payment-box">
    <div class="col-md-6">
      <h3 class="text-dark">Payment Method</h3>
      <div class="card">
        <div class="accordion" id="accordionExample">
          <div class="card">
            <div class="card-header p-0" id="headingTwo">
              <h2 class="mb-0">
                <button class="btn btn-light btn-block text-left collapsed p-3 rounded-0 border-bottom-custom w-100" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  <div class="d-flex align-items-center justify-content-between">
                    <span>Paypal</span>
                    <img src="https://i.imgur.com/7kQEsHU.png" width="30">
                  </div>
                </button>
              </h2>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
              <div class="card-body">
                <input type="text" class="form-control" placeholder="Paypal email">
              </div>
            </div>
          </div>

          <div class="card">
            <div class="card-header p-0">
              <h2 class="mb-0">
                <button class="btn btn-light btn-block text-left p-3 rounded-0 w-100" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  <div class="d-flex align-items-center justify-content-between">

                    <span>Credit card</span>
                    <div class="icons">
                      <img src="https://i.imgur.com/2ISgYja.png" width="30">
                      <img src="https://i.imgur.com/W1vtnOV.png" width="30">
                      <img src="https://i.imgur.com/35tC99g.png" width="30">
                      <img src="https://i.imgur.com/2ISgYja.png" width="30">
                    </div>

                  </div>
                </button>
              </h2>
            </div>

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
              <div class="card-body payment-card-body">

                <span class="font-weight-normal card-text">Card Number</span>
                <div class="input">

                  <i class="fa fa-credit-card"></i>
                  <input type="text" class="form-control" placeholder="0000 0000 0000 0000">

                </div>

                <div class="row mt-3 mb-3">

                  <div class="col-md-6">

                    <span class="font-weight-normal card-text">Expiry Date</span>
                    <div class="input">

                      <i class="fa fa-calendar"></i>
                      <input type="text" class="form-control" placeholder="MM/YY">

                    </div>

                  </div>


                  <div class="col-md-6">

                    <span class="font-weight-normal card-text">CVC/CVV</span>
                    <div class="input">

                      <i class="fa fa-lock"></i>
                      <input type="text" class="form-control" placeholder="000">

                    </div>

                  </div>


                </div>

                <span class="text-muted certificate-text"><i class="fa fa-lock"></i> Your transaction is secured with ssl certificate</span>

              </div>
            </div>
          </div>

        </div>

      </div>

    </div>

    <div class="col-md-6">
        <h3 class="text-dark">Summary</h3>

        <div class="card">

          <div class="d-flex justify-content-between p-3">

            <div class="d-flex flex-column">

              <span>
                <%= @booking.start_island.name %>
                <i class="fas fa-arrow-right px-3"></i>
                <%= @booking.end_island.name %>
              </span>

            </div>

            <div class="mt-1">
              <sup class="super-price">$<%= @distance.round %></sup>
            </div>

          </div>

          <hr class="mt-0 line">

          <div class="p-3">

            <div class="d-flex justify-content-between mb-2">

              <span>Refferal Bonouses</span>
              <span>-$2.00</span>

            </div>

            <div class="d-flex justify-content-between">

              <span>Vat <i class="fa fa-clock-o"></i></span>
              <span>-20%</span>

            </div>


          </div>

          <hr class="mt-0 line">


          <div class="p-3 d-flex justify-content-between">

            <div class="d-flex flex-column">

              <span>Today you pay(US Dollars)</span>
              <small>After 30 days $9.59</small>

            </div>
            <span>$0</span>



          </div>


          <div class="p-3">

            <div class="d-grid gap-2">
                      <button class="main-cta-color-BonWup isl"
                        data-controller="sweetalert"
                        data-action="click->sweetalert#showAlert"
                      >Pay now</button>
            </div>




          </div>




        </div>
    </div>

  </div>
</div>

app/views/bookings/show_qr.html.erb
<div class="container-qr">
    <%= link_to :back, class:"back-btn" do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
	<div class="ticket airline">
		<div class="top">
			<h1 id="tel-title">Teleportation pass</h1>
			<div class="big">
				<p class="from"><%= @booking.start_island.abbreviation %></p>
				<p class="to"><i class="fas fa-arrow-right"></i> <%= @booking.end_island.abbreviation %></p>
			</div>
			<div class="top--side">
				<%= image_tag 'portal_icon.png', class:'portal-img mb-2' %>
				<p><%= @booking.start_island.assembly_point %></p>
				<p><%= @booking.end_island.assembly_point %></p>
			</div>
		</div>
		<div class="bottom">
			<div class="column-ticket">
				<div class="row-ticket row-1">
					<p><span>Teleportation Date</span>
            <%= @booking.start_date.strftime("%A, %d %B %Y") %>
          </p>
					<p class="row--right"><span>Portal no</span><%= @booking.id % 5 + 1 %></p>
				</div>
				<div class="row-ticket row-2">
					<p><span>Boards</span>
          <%= @booking.start_date.strftime("%I:%M %p")
            %>
          </p>
					<p class="row--center"><span>Departs</span>
            <%= @booking.start_date.advance(minutes: 2).strftime("%I:%M %p")
            %></p>
					<p class="row--right">
            <span>Arrives</span>
            <%= @booking.start_date.advance(minutes: 4).strftime("%I:%M %p") %>
            </p>
				</div>
				<div class="row-ticket row-3">
					<p><span>Passenger</span>
          <%= "#{current_user.first_name} #{current_user.last_name}" %>
          </p>
					<p class="row--center"><span>Queue no</span><%= @booking.id % 4 + 1 %></p>
					<p class="row--right"><span>Group</span><%= @booking.id % 2 + 1 %></p>
				</div>
			</div>
			<div class="bar--code"></div>
		</div>
	</div>
</div>