config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {}

  root to: "pages#home"
  get "about", to: "pages#about"
  get "contact", to: "contacts#new"
  get "policies", to: "pages#policies"

  resources :contacts, only: [:new, :create]
  get "blog", to: "pages#blog"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :bookings, only: [:index, :show, :destroy, :update, :new, :create] do
    member do
      get :payment
      get :show_qr
      patch :accept
      patch :decline
    end
  end

  resources :islands, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <!-- Grid container -->
  <div class="container">
    <!-- Section: Links -->
    <section class="mt-5">
    </section>
    <!-- Section: Links -->

    <hr class="my-5" />

    <!-- Section: Social -->
    <section class="text-center mb-5">
      <a href="" class="text-white me-4">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="text-white me-4">
        <i class="fa-brands fa-x-twitter"></i>
      </a>
      <a href="" class="text-white me-4">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="text-white me-4">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="text-white me-4">
        <i class="fab fa-github"></i>
      </a>
    </section>
    <!-- Section: Social -->

    <!-- Copyright -->
    <div class="foot-bot text-center d-flex justify-content-between p-3">
      <p>Copyright &copy; 2024</p>
      <%= link_to "Privacy Policy", "/policies", class: "text-white" %>
      <h6>Made with <i class="fas fa-heart fa-beat"></i> by the Crazy Chicken Team 🐣</h6>
    </div>
    <!-- Copyright -->
  </div>
  <!-- Grid container -->
</footer>

app/views/shared/_login_modal.html.erb
  <!-- Modal -->
  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content rounded-4">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="loginModalLabel">Ready to teleport to your dream destination? </h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Sign up or log in now to start your journey hassle-free! Create an account today for seamless booking.
        </div>
        <div class="modal-footer">
          <button type="button" class="adv-btn">
          <%= link_to "Access My Account", new_user_registration_path, class: "text-white" %>
          </button>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-chicken anim">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%=image_tag("logo-full.svg") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%
=begin%>
 <button class="btn btn-primary"
      data-action="click->dark-mode#toggle"
    >
      Toggle Mode
    </button> 
<%
=end%>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item active">
            <%= link_to "About", "#about", class: "nav-link" %>
        </li>
        <li class="nav-item active">
            <%= link_to "My Teleportations", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
            <%= link_to "Contact", "/contact", class: "nav-link" %>
        </li>
        <% if user_signed_in? %>

          <li class="nav-item dropdown">

          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.avatar.attached? %>
            <%= image_tag(current_user.avatar,
                            class: "avatar") %>
          <% else %>
            <%= image_tag "logo.png", class: "avatar", alt: "dropdown menu" %>
          <% end %>

          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <% if current_user.admin? %>
                <%= link_to "Admin Platform", '/admin', class: "dropdown-item" %>
              <% end %>
              <%= link_to "View Teleportations", bookings_path, class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link secondary-cta-sign" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link main-cta-color-BonWup" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</div>