config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {}

  root to: "pages#home"
  get "about", to: "pages#about"
  get "contact", to: "contacts#new"
  get "policies", to: "pages#policies"

  resources :contacts, only: [:new, :create]
  get "blog", to: "pages#blog"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :bookings, only: [:index, :show, :destroy, :update, :new, :create] do
    member do
      get :payment
      get :show_qr
      patch :accept
      patch :decline
    end
  end

  resources :islands, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!
  def new
    @contact = Contact.new
  end
  def create
    @contact = Contact.new(contact_params)
    if  @contact.save
      redirect_to root_path, notice: "Your message has been successfully submitted."
    else

      render :new
    end
  end


  private
  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/views/contacts/new.html.erb
<div class='login-form mt-4'>
  <div class="form-logo">
    <%= image_tag "logo-full.svg" %>
  </div>



  <div class= "card border-dark mb-3 p-5 mx-auto log-card" style="width: 50%;">
    <div class= "card-body text-dark">
          <h1>Contact us</h1>
          <%= simple_form_for @contact, url: contacts_path do |f| %>
          <%= f.input :name, label: 'Full name' %>
          <%= f.input :email, label: 'Email' %>
          <%= f.input :message, label: 'Message', as: :text %>
          <% if @show_checkbox_recaptcha %>
            <%= recaptcha_tags %>
          <% else %>
            <%= recaptcha_v3(action: 'login', class: 'btn main-cta-color', site_key: ENV['RECAPTCHA_SITE_KEY_V3']) %>
          <% end %>
            <%= f.button :submit, "Submit Your Request", class: 'btn main-cta-color-BonWup' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>